/*
 * This file is generated by jOOQ.
*/
package sages.bootcamp.example.jooq;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import sages.bootcamp.example.jooq.tables.Cars;
import sages.bootcamp.example.jooq.tables.records.CarsRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CarsRecord, Long> IDENTITY_CARS = Identities0.IDENTITY_CARS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CarsRecord> CARS_PKEY = UniqueKeys0.CARS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CarsRecord, Long> IDENTITY_CARS = createIdentity(Cars.CARS, Cars.CARS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CarsRecord> CARS_PKEY = createUniqueKey(Cars.CARS, "cars_pkey", Cars.CARS.ID);
    }
}
