/*
 * This file is generated by jOOQ.
*/
package sages.bootcamp.example.jooq;


import javax.annotation.Generated;

import sages.bootcamp.example.jooq.tables.Cars;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.cars</code>.
     */
    public static final Cars CARS = sages.bootcamp.example.jooq.tables.Cars.CARS;
}
